pipeline {
  agent any
  parameters {
    string(defaultValue: "", description: "Deployment name", name: "deploymentName")
    choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "AWS Availability Zone", name: "awsAz")
    booleanParam(defaultValue: false, description: "Confirm deployment?", name: "confirmDeploy")
  }

  stages {
    stage("Deployment") {
      steps {
        echo "Deployment name is: ${params.deploymentName} \n"
        echo "AWS AZ is: ${params.awsAz} \n"
        echo "Confirm deployment? ${params.confirmDeploy} \n"
      }
    }
  }
}