pipeline {
  agent any
  stages {
    stage("Stage 1") {
      steps {
        echo "Print Stage1"
      }
    }
    stage("Stage 2") {
      steps {
        echo "Print Stage2"
      }
    }
    stage("Stage 3") {
      steps {
        echo "Print Stage3"
      }
    }
    stage("Stage 4") {
      steps {
        echo "Print Stage4"
      }
    }
    stage("Stage 5") {
      steps {
        echo "Print Stage5"
      }
    }
    stage("Success!") {
      steps {
        echo "Stages 1 to 5 printed!"
      }
    }
  }
}